@echo off
echo Stoppe alle Java-Prozesse...
taskkill /f /im java.exe >nul 2>&1
echo Warte 2 Sekunden...
timeout /t 2 /nobreak >nul
echo Führe Maven Clean aus...
call mvn clean
echo Starte Anwendung...
call mvn javafx:run
