title: "Der Gott von Demirantha"
subtitle: "Roman von Gerald Leonard"
author: "Gerald Leonard"
rights: "© 2025 Gerald Leonard"
date: "Oktober 2025"
lang: "de-DE"
cover-image: "cover_image.png"
abstract: |
  Nach den Ereignissen in Königsstadt steht Demirantha am Rande des Zusammenbruchs.
  Kata, Jomar und ihr Sohn Ayen müssen erkennen, dass selbst die Götter nicht ewig wachen.
subject: ["Fantasy", "Roman"]
publisher: "Eigenverlag"